name: 'Update schedule'

on:
  schedule:
    - cron: '0 17,7 * * *'
  workflow_dispatch:
    branches:
      - master
      - dev
      - gd
jobs:
  push:
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 120
    strategy:
      matrix:
        operating-system: [ 'ubuntu-20.04' ]
    steps:
      - name: Set branch name
        id: vars
        run: echo "BRANCH_NAME=${{ github.repository_owner == 'Guovin' && 'gd' || 'master' }}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
      - name: Run with setup-python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          update-environment: true
          cache: 'pipenv'
      - name: Check open_driver config
        id: check_driver
        run: |
          echo "OPEN_DRIVER=$(python -c '
          try:
            from utils.config import config
            open_driver = config.open_driver
          except:
            open_driver = False
          print(open_driver)')" >> $GITHUB_ENV
      - name: Set up Chrome
        if: env.OPEN_DRIVER == 'True'
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - name: Download chrome driver
        if: env.OPEN_DRIVER == 'True'
        uses: nanasess/setup-chromedriver@master
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - name: Install pipenv
        run: pip3 install --user pipenv
      - name: Install dependecies
        run: pipenv --python 3.13 && pipenv install --deploy
      - name: Install selenium
        if: env.OPEN_DRIVER == 'True'
        run: pipenv install selenium
      - name: Update
        run: pipenv run dev
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Github Action Auto Updated"
            git push --force
          fi
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repo
        uses: actions/checkout@v4

      - name: Download File from GitHub
        run: |
          # 示例：直接下载某个文件（替换为实际URL）
          curl -o IPV4.txt https://raw.githubusercontent.com/jerome158/LIVETV/master/output/userresult.txt
          curl -o IPV6.txt https://raw.githubusercontent.com/jerome158/LIVETV/master/output/ipv6/result.txt

      - name: Clone Gitee Repo
        env:
          GITEE_USER: ${{ secrets.GITEE_USER }}
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
          GITEE_REPO: ${{ secrets.GITEE_REPO }}
        run: |
          git clone "https://${GITEE_USER}:${GITEE_TOKEN}@gitee.com/${GITEE_USER}/${{ secrets.GITEE_REPO }}.git"
          cd ${{ secrets.GITEE_REPO }}

      - name: Copy File & Push to Gitee
        env:
          GITEE_USER: ${{ secrets.GITEE_USER }}
          GITEE_REPO: ${{ secrets.GITEE_REPO }}
        run: |
          cd ${{ secrets.GITEE_REPO }}
          git config user.name "Auto Sync"
          git config user.email "auto-sync@users.noreply.github.com"
          # 替换文件
          cp ../IPV4.txt ./IPV4.txt
          cp ../IPV6.txt ./IPV6.txt
          git add IPV4.txt IPV6.txt
          # Check for changes and commit only if there are any
          if ! git diff --cached --quiet; then
            git commit -m "Sync file from GitHub $(date)"
            git push -f origin master
          else
            echo "No changes to commit"
          fi
